### ISSUE TITLE
nix 2.0?

### ISSUE THREAD

**Issue by Mic92** [LnL7/nix-docker#14]
This could need an update.

**Comment by LnL7** [comment]
I ran into some kind of problem with nix-env, didn't look into it any further yet.

```
building '/nix/store/gn4yxdxzzw6qvmrwfbbd1ql6bv3prsmv-user-environment.drv'...
while setting up the build environment: executing '/nix/store/lg0s7z1bvj2chimz3a4qax3y8ssw45m3-nix-2.0/libexec/nix/buildenv': Permission denied
builder for '/nix/store/gn4yxdxzzw6qvmrwfbbd1ql6bv3prsmv-user-environment.drv' failed with exit code 1
error: build of '/nix/store/gn4yxdxzzw6qvmrwfbbd1ql6bv3prsmv-user-environment.drv' failed
```

**Comment by LnL7** [comment]
This looks pretty suspicious to me, but I'm not sure where to go from there.

```
[pid 13227] seccomp(SECCOMP_SET_MODE_STRICT, 1, NULL) = -1 EINVAL (Invalid argument)
```

https://gist.github.com/LnL7/e6b613f4016a60c3c478d4c078af8212#file-gistfile1-txt-L27

**Comment by Mic92** [comment]
@LnL7 do you have branch for, I could try this? I am pretty familiar with linux os sandboxing internals.

**Comment by LnL7** [comment]
[nix-wip](https://github.com/LnL7/nix-docker/commits/nix-wip) or do you want an image?

**Comment by Mic92** [comment]
that should be ok.

**Comment by Mic92** [comment]
@LnL7 do your run docker on nixos? Do you have any non-standard options?

**Comment by Mic92** [comment]
Or does your error happen during docker build?

**Comment by Mic92** [comment]
Dockerfiles are also working for me.

**Comment by Mic92** [comment]
Ah, no. Now I can reproduce it.

**Comment by Mic92** [comment]
Let's get swifty: https://github.com/Mic92/cntr :)

**Comment by Mic92** [comment]
I first guessed it was a special syscall filter being applied during `docker build`. But I get the same error when using cntr, so it must be something else. I will digger deeper.

**Comment by Mic92** [comment]
That seccomp error is not the actual problem.

**Comment by LnL7** [comment]
Thanks for the help with debugging!
