### ISSUE TITLE
Help using nix-docker with nix-daemon locally

### ISSUE THREAD

**Issue by yurrriq** [LnL7/nix-docker#2]
On my `nix-darwin` system, I use `nix-daemon`. I've gotten `nix-docker` set up per the README, but when I try to build something it complains about there not being a `nibbled` group on the Docker container. I'm not really sure where to go from here... Any advice?

Related: https://github.com/LnL7/nix-darwin/issues/9

**Comment by LnL7** [comment]
That's strange, the container has a nixbld group and some build users https://github.com/LnL7/nix-docker/blob/master/default.nix#L25

**Comment by yurrriq** [comment]
Aha, I was using `lnl7/nix:ssh`.

```fish
docker run --restart always --name nix-docker -d -p 3022:22 lnl7/nix:ssh
```
