### ISSUE TITLE
does not bootstrap system.build.etc aka /etc/ which means you should probably avoid nix-docker until it does

### ISSUE THREAD

**Issue by ghuntley** [LnL7/nix-docker#25]
Howdy Daiderd,

A quick GitHub issue to say that I appreciate the work you are doing. I don't have time atm to send in a pull-request but here's a repro. Related issues #9 

# repro

```
FROM lnl7/nix:2.1.2

# baseline
RUN nix-env -iA nixpkgs.busybox 

# trust/use these 3rd party caches
RUN nix-env -iA cachix -f https://github.com/NixOS/nixpkgs/tarball/889c72032f8595fcd7542c6032c208f6b8033db6
RUN cachix -v use hie-nix
```

💥

**Comment by LnL7** [comment]
busybox binaries have much less functionality than the gnu versions, installing it globally is generally a bad idea and probably causing problems.

**Comment by ghuntley** [comment]
Ah no. The real issue is system.build.etc aka /etc/ isn't bootstrapped in the docker image. That was just a quick and easy way to demonstrate it.

**Comment by LnL7** [comment]
Not sure what that means.

**Comment by ghuntley** [comment]
https://github.com/NixOS/nixos/blob/master/modules/system/etc/etc.nix

**Comment by ghuntley** [comment]
Bootstrapping etc will fix this problem and  https://github.com/LnL7/nix-docker/issues/9

**Comment by LnL7** [comment]
That's a nixos module. I still don't understand the problem or how it's related to the image.
